n = input('Digite algo :')
print(f'O seu tipo primitivo é {type(n)}')
print(f'é alfabetico? {n.isalpha()}')
print(f'é númerico? {n.isnumeric()}')
print(f'é alfanúmerico? {n.isalnum()}')
print(f'está em caixa alta? {n.isupper()}')
print(f'está em minuscula? {n.islower()}')
print(f'é decimal? {n.isdecimal()}')
print(f'é um digito? {n.isdigit()}')
print(f'é um titulo? {n.istitle()}')